#!/usr/bin/env python3
"""Generate one AprilTag-36h11 marker MODEL per landmark ID: a PNG plus a
matching SDF (a thin emissive plate that carries the tag on its -x face). The
detector reads the tag ID off the image; the plate is parented in the world
just in front of the aisle-facing flange of the corresponding I-beam pillar.

Why -x face: the box maps the texture mirrored on opposite faces and AprilTag
cannot read a mirrored tag, so the spawn always presents the -x face to the
robot (verified detectable in the spike). The launch picks yaw per column so
that -x face looks into the aisle.

Run inside the container (OpenCV lives there):
  python3 gen_marker_models.py --ids 1 2 3 4 5 6 7 8 --out <config/aruco dir> \
      --texture-dir /home/ros/ws/src/pro_lab_filters/config/aruco

--texture-dir is the absolute IN-CONTAINER path gz uses to load the PNG
(albedo/emissive map paths in SDF must be absolute or on GZ_SIM_RESOURCE_PATH).
"""
import argparse
import os
import cv2
import numpy as np


def make_marker(dictionary, marker_id, marker_px=600, border_frac=0.18):
    if hasattr(cv2.aruco, "generateImageMarker"):
        m = cv2.aruco.generateImageMarker(dictionary, marker_id, marker_px)
    else:
        m = cv2.aruco.drawMarker(dictionary, marker_id, marker_px)
    b = int(round(marker_px * border_frac))
    canvas = np.full((marker_px + 2 * b, marker_px + 2 * b), 255, np.uint8)
    canvas[b:b + marker_px, b:b + marker_px] = m
    return canvas


SDF_TEMPLATE = """<?xml version="1.0"?>
<!-- AprilTag-36h11 marker plate for landmark id={mid}. Auto-generated by
     gen_marker_models.py - do not edit by hand. The tag sits on the -x face;
     the experiment launch spawns this offset from pillar {mid} toward the
     aisle, with yaw chosen so the -x face looks at the robot. emissive_map
     keeps the tag readable regardless of warehouse lighting. SIZE is the
     marker side incl. quiet-zone border (~0.8 m gives ~69 px at 7.5 m). -->
<sdf version="1.8">
  <model name="marker_{mid:02d}">
    <static>true</static>
    <link name="link">
      <pose>0 0 {zc} 0 0 0</pose>
      <visual name="tag">
        <geometry><box><size>0.04 {size} {size}</size></box></geometry>
        <material>
          <ambient>1 1 1 1</ambient>
          <diffuse>1 1 1 1</diffuse>
          <specular>0 0 0 1</specular>
          <pbr>
            <metal>
              <albedo_map>{tex}/marker_{mid:02d}.png</albedo_map>
              <emissive_map>{tex}/marker_{mid:02d}.png</emissive_map>
              <metalness>0.0</metalness>
              <roughness>1.0</roughness>
            </metal>
          </pbr>
        </material>
      </visual>
    </link>
  </model>
</sdf>
"""


# Textured COLLADA quad (Z-up) carrying the tag PNG, for RViz MESH_RESOURCE
# markers so the detector can draw the ACTUAL tag image (not a plain plate).
# Quad lies in the local Y-Z plane (normal +x), size SIZE square, centred at
# origin; the detector yaws it to face the robot. Texture is bound to both
# diffuse and emission so it stays readable under RViz lighting.
DAE_TEMPLATE = """<?xml version="1.0" encoding="utf-8"?>
<COLLADA xmlns="http://www.collada.org/2005/11/COLLADASchema" version="1.4.1">
 <asset><up_axis>Z_UP</up_axis></asset>
 <library_images>
  <image id="tagtex"><init_from>marker_{mid:02d}.png</init_from></image>
 </library_images>
 <library_effects>
  <effect id="eff">
   <profile_COMMON>
    <newparam sid="surf"><surface type="2D"><init_from>tagtex</init_from></surface></newparam>
    <newparam sid="samp"><sampler2D><source>surf</source></sampler2D></newparam>
    <technique sid="t"><lambert>
     <emission><texture texture="samp" texcoord="UVSET0"/></emission>
     <diffuse><texture texture="samp" texcoord="UVSET0"/></diffuse>
    </lambert></technique>
   </profile_COMMON>
  </effect>
 </library_effects>
 <library_materials>
  <material id="mat"><instance_effect url="#eff"/></material>
 </library_materials>
 <library_geometries>
  <geometry id="geo"><mesh>
   <source id="pos"><float_array id="posarr" count="12">0 {neg} {neg} 0 {pos} {neg} 0 {pos} {pos} 0 {neg} {pos}</float_array>
    <technique_common><accessor source="#posarr" count="4" stride="3">
     <param name="X" type="float"/><param name="Y" type="float"/><param name="Z" type="float"/>
    </accessor></technique_common></source>
   <source id="uv"><float_array id="uvarr" count="8">0 0 1 0 1 1 0 1</float_array>
    <technique_common><accessor source="#uvarr" count="4" stride="2">
     <param name="S" type="float"/><param name="T" type="float"/>
    </accessor></technique_common></source>
   <vertices id="vtx"><input semantic="POSITION" source="#pos"/></vertices>
   <triangles count="2" material="mat">
    <input semantic="VERTEX" source="#vtx" offset="0"/>
    <input semantic="TEXCOORD" source="#uv" offset="1" set="0"/>
    <p>0 0 1 1 2 2 0 0 2 2 3 3</p>
   </triangles>
  </mesh></geometry>
 </library_geometries>
 <library_visual_scenes><visual_scene id="scene"><node>
   <instance_geometry url="#geo"><bind_material><technique_common>
    <instance_material symbol="mat" target="#mat">
     <bind_vertex_input semantic="UVSET0" input_semantic="TEXCOORD" input_set="0"/>
    </instance_material>
   </technique_common></bind_material></instance_geometry>
 </node></visual_scene></library_visual_scenes>
 <scene><instance_visual_scene url="#scene"/></scene>
</COLLADA>
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ids", type=int, nargs="+", required=True)
    ap.add_argument("--out", required=True, help="dir to write PNGs + SDFs")
    ap.add_argument("--texture-dir", required=True,
                    help="absolute in-container path gz uses to load the PNG")
    ap.add_argument("--marker-px", type=int, default=600)
    ap.add_argument("--size", type=float, default=0.8, help="plate side [m]")
    ap.add_argument("--zc", type=float, default=0.4, help="plate centre height [m]")
    ap.add_argument("--dict", default="DICT_APRILTAG_36h11")
    args = ap.parse_args()

    os.makedirs(args.out, exist_ok=True)
    dict_id = getattr(cv2.aruco, args.dict)
    dictionary = cv2.aruco.Dictionary_get(dict_id) \
        if hasattr(cv2.aruco, "Dictionary_get") \
        else cv2.aruco.getPredefinedDictionary(dict_id)

    for i in args.ids:
        png = os.path.join(args.out, f"marker_{i:02d}.png")
        cv2.imwrite(png, make_marker(dictionary, i, args.marker_px))
        sdf = os.path.join(args.out, f"marker_{i:02d}.sdf")
        with open(sdf, "w") as f:
            f.write(SDF_TEMPLATE.format(mid=i, size=args.size, zc=args.zc,
                                        tex=args.texture_dir.rstrip("/")))
        dae = os.path.join(args.out, f"marker_{i:02d}.dae")
        h = args.size / 2.0
        with open(dae, "w") as f:
            f.write(DAE_TEMPLATE.format(mid=i, pos=f"{h:.4f}", neg=f"{-h:.4f}"))
        print(f"wrote {png} + {sdf} + {dae}")


if __name__ == "__main__":
    main()
